services:
  # web - apache2/php
  web:
    build:
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - /var/www/html/app/tmp
      - ./cakephp:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  # db - mysql
  db:
    image: mysql:5.7.41
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./sql/combined.sql:/docker-entrypoint-initdb.d/combined.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  # database management - adminer
  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hever

volumes:
  mysqldata: {}
